### ISSUE TITLE
how to change frame per second

### ISSUE THREAD

**Issue by PRAJWLSHETTY** [azhartalha/Traffic-Survalance-with-Computer-Vision-and-Deep-Learning#2]
I have tried changing different fps values but the code seems to process the videos very slow. Any suggestions on how to make it run faster.

**Comment by azhartalha** [comment]
Firstly sorry for a late reply. 
Please understand that in most of the DL applications the computation involved is very high due to the complexity of Neural Networks.
However, I suggest the use of GPU and install tensorflow GPU and try again.
