### ISSUE TITLE
 module 'tensorflow' has no attribute 'space_to_depth'

### ISSUE THREAD

**Issue by Water2style** [azhartalha/Traffic-Survalance-with-Computer-Vision-and-Deep-Learning#5]
what strange is it occurs " File "C:\Users\syeda\Desktop\work\YAD2K-master\yad2k\models\keras_yolo.py", line 32, in space_to_depth_x2" 
.....  i even do not have the path of the files.......

**Comment by xiphixiongfei** [comment]
hello， could you tell me what‘s the problem? thanks a lot
